#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $KITTY_REPO == "kittyuserbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2l0c3NpbXBsZTEvS2l0dHl1c2VyYm90L3RyZWUvbWFpbi56aXA=" | base64 -d
    elif [[ $KITTY_REPO == "KITTYUSERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2l0c3NpbXBsZTEvS2l0dHl1c2VyYm90L3RyZWUvbWFpbi56aXA=" | base64 -d
    elif [[ $KITTY_REPO =~ $regex ]]
    then
        if [[ $KITTY_REPO_BRANCH ]]
        then
            echo "${KITTY_REPO}/tree/${KITTY_REPO_BRANCH}.zip"
        else
            echo "${KITTY_REPO}/tree/main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2l0c3NpbXBsZTEvS2l0dHl1c2VyYm90L3RyZWUvbWFpbi56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="mafiabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    KITTYPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $KITTYPATH
    echo "    Starting KITTY USERBOT  "
    echo "
                          Kitty
                          Kitty
                          Kitty
                          Kitty

    "

    python3 ./setup/updater.py ./requirements.txt requirements.txti
    python3 -m userbot
}

_set_bot
